[package]
name = "example_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bowtie = { path = "../engine" }
glfw = "0.45.0"
futures = "0.3"
gl = "0.14.0"
rand = "0.8.5"
